ALTER TABLE "User" ADD COLUMN "hideLikeName" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "SongLike" ADD COLUMN "title" TEXT;
ALTER TABLE "SongLike" ADD COLUMN "artist" TEXT;
ALTER TABLE "SongLike" ADD COLUMN "album" TEXT;
